# Generated by Django 4.1.7 on 2023-04-01 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="AddressBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11)),
                ("governorate", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
                ("building", models.CharField(max_length=50)),
                ("floor", models.CharField(max_length=50)),
                ("landmark", models.CharField(blank=True, max_length=150, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Address Book",
                "db_table": "profiles_address_book",
            },
        ),
    ]
