# Generated by Django 4.1.7 on 2023-05-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressbook",
            name="address_type",
            field=models.CharField(
                choices=[("H", "Home"), ("O", "Office")], default="H", max_length=1
            ),
        ),
    ]
