# Generated by Django 4.1.7 on 2023-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_addressbook_address_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressbook",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
