# Generated by Django 4.1.7 on 2023-03-31 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_alter_cart_customer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartproduct",
            name="unique_cart_product",
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartproduct",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="cartproduct",
            table="carts_cart_products",
        ),
    ]
