# Generated by Django 4.1.7 on 2023-03-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_remove_cartproduct_unique_cart_product_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartproduct",
            constraint=models.UniqueConstraint(
                models.F("product"), models.F("cart"), name="unique_cart_product"
            ),
        ),
    ]
