# Generated by Django 4.1.7 on 2023-03-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="email_verified_at",
            field=models.DateTimeField(null=True),
        ),
    ]
