# Generated by Django 4.1.7 on 2023-04-08 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_brand_product_productimage_seller_and_more"),
        ("accounts", "0002_customer_email_verified_customer_email_verified_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.staff",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="shop.seller",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff",
                "db_table": "sellers_staff",
            },
            bases=("accounts.user",),
        ),
    ]
