# Generated by Django 4.1.7 on 2023-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_storerepresentative"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(default=201001465756, max_length=13),
            preserve_default=False,
        ),
    ]
