# Generated by Django 4.1.7 on 2023-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="two_fa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
