# Generated by Django 4.1.7 on 2023-05-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_options_brand_name_ar_brand_name_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "منتج", "verbose_name_plural": "المنتجات"},
        ),
        migrations.RemoveField(
            model_name="brand",
            name="name_ar",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="slug_ar",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="slug_en",
        ),
        migrations.RemoveField(
            model_name="store",
            name="name_ar",
        ),
        migrations.RemoveField(
            model_name="store",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="store",
            name="slug_ar",
        ),
        migrations.RemoveField(
            model_name="store",
            name="slug_en",
        ),
    ]
