# Generated by Django 4.1.7 on 2023-05-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_product_options_remove_brand_name_ar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterField(
            model_name="product",
            name="in_stock",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spec", models.CharField(max_length=100)),
                ("spec_en", models.CharField(max_length=100, null=True)),
                ("spec_ar", models.CharField(max_length=100, null=True)),
                ("value", models.CharField(max_length=250)),
                ("value_en", models.CharField(max_length=250, null=True)),
                ("value_ar", models.CharField(max_length=250, null=True)),
                (
                    "lookup_field",
                    models.CharField(editable=False, max_length=200, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
