# Generated by Django 4.1.7 on 2023-05-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_productcolor_productsize_remove_productimage_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
    ]
