# Generated by Django 4.1.7 on 2023-04-01 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("orders", "0002_orderproduct_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="profiles.addressbook",
            ),
            preserve_default=False,
        ),
    ]
