# Generated by Django 4.1.7 on 2023-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderchangehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderchangehistory",
            name="location",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="orderchangehistory",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Carrier picked up the package."),
                    (1, "Package arrived at our facility"),
                    (2, "Package departed our facility"),
                    (3, "Package arrived at the final delivery station"),
                    (4, "Out for delivery"),
                    (5, "Delivered"),
                ]
            ),
        ),
    ]
